version: '3.3'

services:
  mongo:
    image: mongo:4.2.22
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwd123
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    # ports:
    #   - "27017:27017"
    volumes:
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
